### ISSUE TITLE
Font size setting please! 

### ISSUE THREAD

**Issue by beeflin** [gabrielglbh/Kan-Practice#148]
My eyes aren't too good so please can I have the option of changing text size? Also, please, a pure (blackout) dark mode for best contrast.

**Comment by gabrielglbh** [comment]
Font sizes will not change as for now, but I added a more blackout mode for best contrast when in dark mode in the latest release.

**Comment by beeflin** [comment]
Thank you! --Steve Rogers 07866 680370 The Difference ***@***.*** Serving the client, not the machine On 18 Oct 2023 09:10, Gabriel García ***@***.***> wrote:
Font sizes will not change as for now, but I added a more blackout mode for best contrast when in dark mode in the latest release.
