### ISSUE TITLE
Correct German translations for 1.1.0

### ISSUE THREAD

**Issue by gabrielglbh** [gabrielglbh/Kan-Practice#19]
Hey there @aruffj, hope you are doing well! Version 1.1.0 is coming hot and I would love that you review the german translations I made using DeepL. Whenever this is done, please, create a PR to the branch 1.1.0 :). Thank you very much in advance!!!

**Comment by synthie-cat** [comment]
Hey,
I am really busy at the moment, earliest I have bandwidth would be Monday. Is that early enough for you?

**Comment by gabrielglbh** [comment]
@aruffj Monday is perfect. Don't worry about it. :)

**Comment by gabrielglbh** [comment]
@aruffj All related 1.1.0 translations can be seen on #20 on the `de.json` file. When creating the PR with all the fixed translations, please, make the PR to the 1.1.0 branch!

**Comment by gabrielglbh** [comment]
I will be launching the 1.1.0 app later today, would you be able to review the translations? If not, I will move this issue to the 1.2.0 milestone and leave it to the next release! Happy Christimas @aruffj :)

**Comment by synthie-cat** [comment]
Sorry, quite delayed on my side. Can start at 4pm GMT+1 :) when would you like to release? 

⁣Gesendet mit BlueMail ​

**Comment by gabrielglbh** [comment]
No worries mate. I would like to release the new version around 11PM GMT + 1, so you have plenty of time to work with!

**Comment by synthie-cat** [comment]
[de.zip](https://github.com/gabrielglbh/Kan-Practice/files/7756494/de.zip)

Currently unable to create my own PR - but here you go. :)

Could you specify again what you mean with Line 39: "Copy to Pron"? The German translation from DeepL ("Beton" meaning: Concrete) seems to be rather non sensical yet searching for "Pron" brings it's own issues. ;)

**Comment by gabrielglbh** [comment]
Oh thank you!! Yup, "Copy to Pron" would be "Copy to Pronunciation". I just truncated the string, and it seems it causes some unwanted confussion hahah.

**Comment by synthie-cat** [comment]
Ah, then change it to "Als Betonung kopieren" in the de.json please :) I also wrote you a chat message on reddit.

Cheers!
